// Generated by build_site.py — edit there, not here.
export const config = { matcher: "/go/:key*" };

// The write is AWAITED (not ctx.waitUntil) — background promises can be
// cancelled once the middleware returns, which silently dropped counts.
// The AbortSignal caps the cost: worst case a dead Upstash delays the
// redirect by 1.5s, and the redirect ALWAYS proceeds.
async function count(base, tok, cmds) {
  try {
    const r = await fetch(base + "/pipeline", {
      method: "POST",
      headers: { Authorization: "Bearer " + tok },
      body: JSON.stringify(cmds),
      signal: AbortSignal.timeout(1500),
    });
    return "write " + r.status;
  } catch (e) {
    return "write failed: " + ((e && e.name) || "error");
  }
}

export default async function middleware(req) {
  // Vercel Marketplace ("Upstash for Redis") injects KV_*; a hand-created
  // Upstash DB injects UPSTASH_*. Accept both.
  const base = process.env.KV_REST_API_URL ||
    process.env.UPSTASH_REDIS_REST_URL;
  const tok = process.env.KV_REST_API_TOKEN ||
    process.env.UPSTASH_REDIS_REST_TOKEN;
  try {
    const u = new URL(req.url);
    const key = (u.pathname.split("/")[2] || "").slice(0, 64);
    if (key === "__health") {
      const state = base && tok
        ? "configured; " + await count(base, tok, [["INCR", "go:__health"]])
        : "NOT configured";
      return new Response("go-counter: live; storage " + state,
        { status: 200, headers: { "content-type": "text/plain" } });
    }
    if (!base || !tok || !/^[\w-]+$/.test(key)) return; // pass through
    const sid = (u.searchParams.get("sid1") || "direct")
      .slice(0, 80).replace(/[^\w.-]/g, "_");
    const day = new Date().toISOString().slice(0, 10);
    await count(base, tok, [
      ["SADD", "go:keys", key],
      ["INCR", "go:" + key + ":total"],
      ["INCR", "go:" + key + ":d:" + day],
      ["HINCRBY", "go:" + key + ":camp", sid, 1],
    ]);
  } catch (e) { /* counting must never break the redirect */ }
  return; // undefined -> Vercel continues to the vercel.json redirect
}
