// Generated by build_site.py — edit there, not here.
export const config = { matcher: "/go/:key*" };

export default function middleware(req, ctx) {
  const base = process.env.UPSTASH_REDIS_REST_URL;
  const tok = process.env.UPSTASH_REDIS_REST_TOKEN;
  let key = "";
  try {
    const u = new URL(req.url);
    key = (u.pathname.split("/")[2] || "").slice(0, 64);
    if (key === "__health") {
      return new Response(
        "go-counter: live; storage " +
        (base && tok ? "configured" : "NOT configured"),
        { status: 200, headers: { "content-type": "text/plain" } });
    }
    if (!base || !tok || !/^[\w-]+$/.test(key)) return; // pass through
    const sid = (u.searchParams.get("sid1") || "direct")
      .slice(0, 80).replace(/[^\w.-]/g, "_");
    const day = new Date().toISOString().slice(0, 10);
    ctx.waitUntil(fetch(base + "/pipeline", {
      method: "POST",
      headers: { Authorization: "Bearer " + tok },
      body: JSON.stringify([
        ["SADD", "go:keys", key],
        ["INCR", "go:" + key + ":total"],
        ["INCR", "go:" + key + ":d:" + day],
        ["HINCRBY", "go:" + key + ":camp", sid, 1],
      ]),
    }).catch(() => {}));
  } catch (e) { /* counting must never break the redirect */ }
  return; // undefined -> Vercel continues to the vercel.json redirect
}
