// Generated by build_site.py — edit there, not here.
export const config = { matcher: "/go/:key*" };

// Affiliate destinations (from AFFILIATE_OFFERS at build time). The same
// map exists as vercel.json redirects — that copy is the fallback when
// this middleware doesn't answer.
const DEST = {
  "descript": "https://www.descript.com/?REPLACE_WITH_YOUR_AFFILIATE_REF",
  "elevenlabs": "https://try.elevenlabs.io/the-ai-shortlist",
  "invideo": "https://invideo.sjv.io/B5Gq7B",
  "jasper": "https://www.jasper.ai/?REPLACE_WITH_YOUR_AFFILIATE_REF",
  "kit": "https://kit.com/?REPLACE_WITH_YOUR_AFFILIATE_REF",
  "notion": "https://www.notion.so/?REPLACE_WITH_YOUR_AFFILIATE_REF",
  "pictory": "https://pictory.ai/?REPLACE_WITH_YOUR_AFFILIATE_REF",
  "surfer": "https://surferseo.com/?REPLACE_WITH_YOUR_AFFILIATE_REF",
  "surveymonkey": "https://www.surveymonkey.com/?REPLACE_WITH_YOUR_AFFILIATE_REF",
  "synthesia": "https://www.synthesia.io/?via=theaishortlist",
  "typeform": "https://www.typeform.com/?REPLACE_WITH_YOUR_AFFILIATE_REF"
};

// The write is AWAITED (not ctx.waitUntil) — background promises can be
// cancelled once the middleware returns, which silently dropped counts.
// The AbortSignal caps the cost: worst case a dead Upstash delays the
// redirect by 1.5s, and the redirect ALWAYS proceeds.
async function count(base, tok, cmds) {
  try {
    const r = await fetch(base + "/pipeline", {
      method: "POST",
      headers: { Authorization: "Bearer " + tok },
      body: JSON.stringify(cmds),
      signal: AbortSignal.timeout(1500),
    });
    return "write " + r.status;
  } catch (e) {
    return "write failed: " + ((e && e.name) || "error");
  }
}

export default async function middleware(req) {
  // Vercel Marketplace ("Upstash for Redis") injects KV_*; a hand-created
  // Upstash DB injects UPSTASH_*. Accept both.
  const base = process.env.KV_REST_API_URL ||
    process.env.UPSTASH_REDIS_REST_URL;
  const tok = process.env.KV_REST_API_TOKEN ||
    process.env.UPSTASH_REDIS_REST_TOKEN;
  try {
    const u = new URL(req.url);
    const key = (u.pathname.split("/")[2] || "").slice(0, 64);
    if (key === "__health") {
      const state = base && tok
        ? "configured; " + await count(base, tok, [["INCR", "go:__health"]])
        : "NOT configured";
      return new Response("go-counter: live; storage " + state,
        { status: 200, headers: { "content-type": "text/plain" } });
    }
    const dest = DEST[key];
    if (!dest) return; // unknown key -> vercel.json / 404 decides
    if (base && tok && /^[\w-]+$/.test(key)) {
      const sid = (u.searchParams.get("sid1") || "direct")
        .slice(0, 80).replace(/[^\w.-]/g, "_");
      const day = new Date().toISOString().slice(0, 10);
      await count(base, tok, [
        ["SADD", "go:keys", key],
        ["INCR", "go:" + key + ":total"],
        ["INCR", "go:" + key + ":d:" + day],
        ["HINCRBY", "go:" + key + ":camp", sid, 1],
      ]);
    }
    // redirect with param merge — same passthrough vercel.json performed
    // (incoming params win over any baked into the destination URL)
    const d = new URL(dest);
    u.searchParams.forEach((v, k) => d.searchParams.set(k, v));
    return Response.redirect(d.toString(), 307);
  } catch (e) { /* counting must never break the redirect */ }
  return; // undefined -> Vercel falls through to the vercel.json redirect
}
